shadow$provide.module$node_modules$$sentry$tracing$dist$errors=function(global,require,module,exports){function errorCallback(){var activeTransaction=utils_2.getActiveTransaction();activeTransaction&&(utils_1.logger.log("[Tracing] Transaction: internal_error -\x3e Global error occured"),activeTransaction.setStatus("internal_error"))}Object.defineProperty(exports,"__esModule",{value:!0});var utils_1=require("module$node_modules$$sentry$utils$dist$index"),utils_2=require("module$node_modules$$sentry$tracing$dist$utils");
exports.registerErrorInstrumentation=function(){utils_1.addInstrumentationHandler("error",errorCallback);utils_1.addInstrumentationHandler("unhandledrejection",errorCallback)}}
//# sourceMappingURL=module$node_modules$$sentry$tracing$dist$errors.js.map
